# Site settings
title: Shannon Reynolds, Realtor
email: ShannonReynolds0514@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/' # the subpath of your site, e.g. /blog/
url: 'http://www.shannonreynolds.realtor' # the base hostname & protocol for your site
permalink: /:year/:title/
twitter_username: shantwastic
github_username:  jmreynolds

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'shannonreynoldsrealtor'

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
